name: Windows NoMachine RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download NoMachine
        run: |
          Invoke-WebRequest -Uri "https://download.nomachine.com/download/8.11/Windows/nomachine_8.11.3_1_x64.exe" -OutFile "nx.exe"

      - name: Install NoMachine
        run: |
          Start-Process -FilePath ".\nx.exe" -ArgumentList "/S" -Wait

      - name: Display IP and Port Info
        run: |
          $ip = (Invoke-RestMethod -Uri "http://ipinfo.io/json").ip
          Write-Host "Connect to: $ip on port 4000 or the default NoMachine port"
