name: LiteManager Server Setup

on: workflow_dispatch

jobs:
  install-litemanager:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download LiteManager Server
        run: |
          Invoke-WebRequest -Uri "https://litemanager.com/soft/litemanager_free_server.msi" -OutFile "lmserver.msi"

      - name: Install LiteManager Server
        run: Start-Process msiexec.exe -ArgumentList "/i lmserver.msi /quiet" -Wait

      - name: Configure Firewall for LiteManager
        run: |
          netsh advfirewall firewall add rule name="LiteManager" dir=in action=allow protocol=TCP localport=5650
          netsh advfirewall firewall add rule name="LiteManager UDP" dir=in action=allow protocol=UDP localport=5650

      - name: Get Public IP
        run: |
          Invoke-RestMethod -Uri "http://ifconfig.me" | Out-File ip.txt
          Get-Content ip.txt
