name: Ubuntu VPS with NoMachine GUI

on:
  workflow_dispatch:

jobs:
  start-vps:
    runs-on: ubuntu-latest
    steps:
    - name: Install XFCE Desktop + NoMachine
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies xrdp wget
        wget https://download.nomachine.com/download/8.11/Linux/nomachine_8.11.3_1_amd64.deb
        sudo dpkg -i nomachine_8.11.3_1_amd64.deb || sudo apt --fix-broken install -y
        sudo ufw allow 4000
        echo "Done installing NoMachine"

    - name: Show IP address
      run: |
        echo "Your public IP is:"
        curl ifconfig.me
